from . import subject_wizard
from . import marks_wizard
from . import config_wizard
from . import exam_config_wizard
from . import session_wizard
from . import weekly_holiday_wizard
from . import student_wizard
from . import teacher_wizard
from . import guardian_wizard
from . import student_promotion_config_wizard
