from . import user
from . import subject
from . import exam
from . import class_config
from . import result_config
from . import result
from . import combined_subject
from . import grade_config
from . import processed_result
from . import holiday
from . import session
from . import week_day
from . import weekly_holiday
from . import processed_final_result
from . import group
from . import class_room
from . import shift
from . import class_room_config
from . import subject_teacher
from . import student_subject_config
from . import yearly_holiday
from . import designation
from . import notice

