from . import student
from . import subject
from . import exam
from . import class_config
from . import result_config
from . import subject_config
from . import result
from . import combined_subject
from . import grade_config
from . import proccessed_result
